version: "3.7"

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - registrum-net
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - registrum-net
    volumes:
      - redis-data:/data
    command: --appendonly yes

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - registrum-net

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8082:8081
    depends_on:
      - redis
    networks:
      - registrum-net

  api:
    build:
      context: api
      target: dev
    image: docker.pkg.github.com/ckanich-classrooms/final-project-dream-team-1/api:dev
    restart: always
    working_dir: /usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongo:27017/registrum-api
      - REDIS_URL=redis://redis
      - BASE_PATH=/api
    ports:
      - 4000:4000
    volumes:
      - ./api:/usr/src/app
      - node_modules_api:/usr/src/app/node_modules
    depends_on: 
      - mongo
      - redis
    networks: 
      - registrum-net

  banner:
    build:
      context: banner
      target: dev
    image: docker.pkg.github.com/ckanich-classrooms/final-project-dream-team-1/banner:dev
    restart: always
    working_dir: /usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongo:27017/registrum-banner
      - REDIS_URL=redis://redis
      - BASE_PATH=/banner
    ports:
      - 4000:4000
    volumes:
      - ./banner:/usr/src/app
      - node_modules_banner:/usr/src/app/node_modules
    depends_on: 
      - mongo
      - redis
    networks: 
      - registrum-net

  client:
    build:
      context: client
      target: dev
    image: docker.pkg.github.com/ckanich-classrooms/final-project-dream-team-1/client:dev
    restart: always
    working_dir: /usr/src/app
    environment: 
      - API_PROXY_URL=http://api:4000
      - BASE_PATH=/api
      - CLIENT_PORT=3000
    ports:
      - 3000:3000
    volumes: 
      - ./client:/usr/src/app
      - node_modules_client:/usr/src/app/node_modules
    networks: 
      - registrum-net

networks:
  registrum-net:
  
volumes: 
  node_modules_api:
  node_modules_banner:
  node_modules_client:
  mongo-data:
  redis-data:
