version: "3"

services:
  api:
    container_name: api
    build: "api"
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/appdb
      - REDIS_URL=redis://redis
      - NODE_ENV=production
      - BASE_URL=/api
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  redis:
    image: redis:alpine
    container_name: redis
  mongo:
    container_name: mongodb
    restart: always
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - nginx-www:/usr/share/nginx/html
    depends_on:
      - client
      - api
    ports:
      - 8080:80
  client:
    container_name: client
    build: "client"
    environment:
      - NODE_ENV=production
    volumes: 
      - nginx-www:/usr/src/app/build

volumes:
  mongo-data:
  nginx-www: