version: "3.7"

services:

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    command: --appendonly yes
    networks: 
      - registrum-net

  mongo:
    restart: always
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks: 
      - registrum-net
      
  api:
    build:
      context: api
      target: prod
    image: docker.pkg.github.com/ckanich-classrooms/final-project-dream-team-1/api:master
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/registrum
      - REDIS_URL=redis://redis
      - NODE_ENV=production
      - BASE_PATH=/api
    depends_on:
      - mongo
      - redis
    networks:
      - registrum-net

  client:
    build:
      context: client
      target: prod
    image: docker.pkg.github.com/ckanich-classrooms/final-project-dream-team-1/client:master
    restart: always
    depends_on:
      - api
    ports:
      - 8080:80
    networks: 
      - registrum-net

networks:
  registrum-net:

volumes:
  mongo-data:
  redis-data:
