version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - kanich-net
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - kanich-net
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - kanich-net
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8082:8081
    depends_on:
      - redis
    networks:
      - kanich-net

networks:
  kanich-net:
