version: "3"

services:
  api:
    container_name: api
    build: "api"
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/registrum
      - REDIS_URL=redis://redis
      - NODE_ENV=production
      - BASE_PATH=/api
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    volumes:
      - redis-data:/data
    command: --appendonly yes
  mongo:
    container_name: mongodb
    restart: always
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
  client:
    container_name: client
    build: "client"
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    ports:
      - 8080:80

volumes:
  mongo-data:
  redis-data:
