version: "3"

services:

  api:
    image: docker.pkg.github.com/ckanich-classrooms/final-project-dream-team-1/api:latest
    restart: always
    environment:
      - API_BASE_PATH=/api
    networks:
      - registrum-net

  banner:
    image: docker.pkg.github.com/ckanich-classrooms/final-project-dream-team-1/banner:latest
    restart: always
    environment:
      - BANNER_BASE_PATH=/banner
    networks:
      - registrum-net

  banner-data:
    image: docker.pkg.github.com/ckanich-classrooms/final-project-dream-team-1/banner-data:latest
    restart: always
    networks:
      - registrum-net

  client:
    image: docker.pkg.github.com/ckanich-classrooms/final-project-dream-team-1/client:latest
    restart: always
    ports:
      - 8080:80
    networks:
      - registrum-net

networks:
  registrum-net:
