apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: registrum-api
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registrum-api-deployment
spec:
  selector:
    matchLabels:
      app: registrum-api
  replicas: 1
  template:
    metadata:
      labels:
        app: registrum-api
    spec:
      containers:
        - name: registrum-api
          image: alexchomiak/registrum-api-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            # * Grab needed environmental variables from secrets
            - name: SENDGRID_EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: SENDGRID_EMAIL
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: SENDGRID_API_KEY
            - name: API_PORT
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: API_PORT
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: MONGODB_URI
            - name: BANNER_URL
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: BANNER_URL
