apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: registrum-api
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registrum-api-deployment
spec:
  selector:
    matchLabels:
      app: registrum-api
  replicas: 1
  template:
    metadata:
      labels:
        app: registrum-api
    spec:
      containers:
        - name: registrum-api
          image: alexchomiak/registrum-api-test:latest
          ports:
            - containerPort: 4000
          env:
            - name: SENDGRID_EMAIL_ADDRESS
              value: notifications@chom.es
            - name: SENDGRID_API_KEY
              value: SG.8-HelloWorld
            - name: API_PORT
              value: "4000"
            - name: API_REDIS_URI
              value: redis://api-redis:6379
            - name: MONGODB_URI
              value: mongodb+srv://alex:chomiak@cluster0-mizbf.azure.mongodb.net/test?retryWrites=true&w=majority

