# ALL SECRETS ARE BASE64
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  SENDGRID_API_KEY: U0cuSGVsbG9Xb3JsZAo= # SG.HelloWorld
  SENDGRID_EMAIL: bm90aWZpY2F0aW9uQGV4YW1wbGUuY29tCg== # notification@example.com
  API_PORT: NDAwMAo= # 4000
  MONGODB_URI: <mongo_uri_here_base64>
  BANNER_URL: aHR0cDovL2Jhbm5lcjo0MDAxL2Jhbm5lcg== # http://banner:4001/banner
---
apiVersion: v1
kind: Secret
metadata:
  name: banner-secrets
type: Opaque
data:
  BANNER_PORT: NDAwMQo= # 4001
  CACHE_TIME: MTAgbWludXRlcwo= # 10 minutes
  MONGODB_URI: <mongo_uri_here_base64>
  API_PROXY_URL: aHR0cDovL2FwaTo0MDAwCg== # http://api:4000
  BANNER_BASE_PATH: L2Jhbm5lcg== # /banner

---
apiVersion: v1
kind: Secret
metadata:
  name: banner-data-secrets
type: Opaque
data:
  REFRESH_INTERVAL: MCAwICogKiAqCg== # 0 0 * * *
