version: '3'

services:
  api:
    image: acmuic.azurecr.io/acm-uic/registrum/api:latest
    restart: always
    environment:
      - API_BASE_PATH=/api
    networks:
      - registrum-net

  banner:
    image: acmuic.azurecr.io/acm-uic/registrum/banner:latest
    restart: always
    environment:
      - BANNER_BASE_PATH=/banner
    networks:
      - registrum-net

  banner-data:
    image: acmuic.azurecr.io/acm-uic/registrum/banner-data:latest
    restart: always
    networks:
      - registrum-net

  client:
    image: acmuic.azurecr.io/acm-uic/registrum/client:latest
    restart: always
    ports:
      - 8080:80
    networks:
      - registrum-net

networks:
  registrum-net:
