name: CI

on:
  push:
  create:
  release:
  pull_request:
  workflow_dispatch:

jobs:
  build-test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
      - name: Restore Package Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Build projects
        run: yarn build
      - name: Run tests
        run: yarn test
      - name: Publish coverage
        run: yarn coverage

  build-push-docker:
    runs-on: ubuntu-latest
    needs:
      - build-test-node
    strategy:
      fail-fast: false
      matrix:
        project: [api, banner, banner-data, client]
    steps:
      - uses: actions/checkout@v2
      - name: Login docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          repository: ${{ github.repository }}/${{ matrix.project }}
          build-args: CLIENT_WEBPUSHPUBLIC=${{ secrets.WEBPUSHPUBLIC }}
          context: .
          file: docker/${{ matrix.project }}.Dockerfile
          push: ${{ (startsWith(github.ref, 'refs/tags/') || (github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/staging')) }}

  trigger-hooks:
    runs-on: ubuntu-latest
    needs:
      - build-push-docker
    steps:
      - name: Trigger Hooks - master
        if: github.ref == 'refs/heads/master'
        run: |
          curl -X POST -H "Content-Type: application/json" -d "{}" '${{ secrets.MASTER_HOOK }}'

      - name: Trigger Hooks - staging
        if: github.ref == 'refs/heads/staging'
        run: |
          curl -X POST -H "Content-Type: application/json" -d "{}" '${{ secrets.STAGING_HOOK }}'

      - name: Trigger Hooks - release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          curl -X POST -H "Content-Type: application/json" -d "{}" '${{ secrets.PROD_HOOK }}'
