name: Docker CI

on: [push, pull_request]

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: client - build and publish image
      run: |
        projects=( api banner banner-data client )
        for project in "${projects[@]}"
        do
          docker build --target $project .
        done
