name: Docker CD - Release

on:
  release:
    tags:
      - v*
    types: [published]

jobs:
  publish-app-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build, push
      run: |
        tag=$(echo ${{ github.ref }} | sed 's/refs\/tags\///g')
        echo tag: $tag

        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin

        projects=( api banner banner-data client )
        for project in "${projects[@]}"
        do
          echo Working on $project ...
          docker build --target $project -t docker.pkg.github.com/${{ github.repository }}/$project:$tag .
          docker tag docker.pkg.github.com/${{ github.repository }}/$project:$tag docker.pkg.github.com/${{ github.repository }}/$project:latest
          docker push docker.pkg.github.com/${{ github.repository }}/$project:$tag
          docker push docker.pkg.github.com/${{ github.repository }}/$project:latest
        done

    - name: Trigger Hooks
      run: |
        curl -X POST -H "Content-Type: application/json" -d "{}" '${{ secrets.PROD_HOOK }}'
