name: Docker CD - Branch

on:
  push:
    branches:
      - master
      - staging*

jobs:
  publish-app-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build, push
      run: |
        branch=$(echo ${GITHUB_REF#refs/heads/})
        rev=$(echo ${GITHUB_SHA} | cut -c1-8)
        echo branch: $branch
        echo rev: $rev

        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin

        projects=( api banner banner-data client )
        for project in "${projects[@]}"
        do
          echo Working on $project ...
          docker build --target $project -t docker.pkg.github.com/${{ github.repository }}/$project:$rev .
          docker tag docker.pkg.github.com/${{ github.repository }}/$project:$rev docker.pkg.github.com/${{ github.repository }}/$project:$branch
          docker push docker.pkg.github.com/${{ github.repository }}/$project:$rev
          docker push docker.pkg.github.com/${{ github.repository }}/$project:$branch
        done
    - name: Trigger Hooks - master
      if: github.ref == 'refs/heads/master'
      run: |
        curl -X POST -H "Content-Type: application/json" -d "{}" ${{ secrets.MASTER_HOOK }}
    - name: Trigger Hooks - staging
      if: github.ref == 'refs/heads/master'
      run: |
        curl -X POST -H "Content-Type: application/json" -d "{}" ${{ secrets.STAGING_HOOK }}

