name: Docker CI

on: [push, pull_request]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          docker-compose build
      