name: Docker CD - Release

on:
  release:
    tags:
      - v*
    types: [published]

jobs:
  publish-app-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build, push
      shell: pwsh
      run: |
        $tag="${{ github.ref }}".Split("refs/tags/")[1]
        Write-Host tag: $tag

        docker login ${{ secrets.REGISTRY_HOST }} --username ${{ secrets.REGISTRY_USER }} --password ${{ secrets.REGISTRY_PASSWORD }}

        docker build -t registrum_base -f Base.Dockerfile .

        $projects=@("api", "banner", "banner-data", "client")
        foreach($project in $projects) {
          Write-Host Working on $project ...
          docker build --target $project -t acmuic.azurecr.io/${{ github.repository }}/$($project):$tag .
          docker tag acmuic.azurecr.io/${{ github.repository }}/$($project):$tag acmuic.azurecr.io/${{ github.repository }}/$($project):latest
          docker push acmuic.azurecr.io/${{ github.repository }}/$($project):$tag
          docker push acmuic.azurecr.io/${{ github.repository }}/$($project):latest
        }

    - name: Trigger Hooks
      run: |
        curl -X POST -H "Content-Type: application/json" -d "{}" '${{ secrets.PROD_HOOK }}'
