name: Docker CD - Branch

on:
  push:
    branches:
      - master
      - staging*

jobs:
  publish-app-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set vars
      shell: bash
      run: |
        echo ::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})
        echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})
    - name: docker build, push
      shell: bash
      run: |
        echo branch: ${{ steps.extract_branch.outputs.branch }}
        echo rev: ${{ steps.extract_branch.outputs.sha_short }}

        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin

        projects=( api banner banner-data client )
        for project in "${projects[@]}"
        do
          echo Working on $project ...
          docker build --target $project -t docker.pkg.github.com/${{ github.repository }}/$project:${{ steps.extract_branch.outputs.sha_short }} .
          docker tag docker.pkg.github.com/${{ github.repository }}/$project:${{ steps.extract_branch.outputs.sha_short }} docker.pkg.github.com/${{ github.repository }}/$project:${{ steps.extract_branch.outputs.branch }}
          docker push docker.pkg.github.com/${{ github.repository }}/$project:${{ steps.extract_branch.outputs.sha_short }}
          docker push docker.pkg.github.com/${{ github.repository }}/$project:${{ steps.extract_branch.outputs.branch }}
        done
