name: Node CI

on: [push, pull_request]

jobs:

  build-rush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v1
        with:
          path: common/temp/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('common/config/rush/shrinkwrap.yml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Start Docker for Mongodb
        run: docker run -d -p 27017:27017 mongo
      - name: Start Docker for redis
        run: docker run -d  -p 6379:6379 redis
      - name: rush install
        run: node common/scripts/install-run-rush.js install --no-link
      - name: rush link
        run: node common/scripts/install-run-rush.js link
      - name: rush lint
        run: node common/scripts/install-run-rush.js lint
      - name: rush build
        run: node common/scripts/install-run-rush.js build --verbose
      - name: rush test
        run: node common/scripts/install-run-rush.js test
      - name: rush coverage
        run: node common/scripts/install-run-rush.js coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
